### ISSUE TITLE
Retirer le script de navigation en haut à droite

### ISSUE THREAD

**Issue by MissGeek** [dixy/Connectix-Boards#3]
Tu te souviens de ce menu de navigation en haut à droite sur la bêta ?
Je te mets le lien de la bêta pour que tu puisses le voir : http://beta.connectix-boards.org/
Si JS est activé, tu devrais normalement voir "Navigavtion" en haut à droite et tu peux cliquer pour le déployer.

Je me souviens que ça n'avait pas soulevé les foules.  Et à force de fréquenter Alsacréations, j'ai lu au sujet du fait d'éviter les raccourcis-clavier qui pourraient interférer avec les raccourcis du navigateur et du lecteur d'écran des non-voyants.
Donc un script comme celui-ci risque justement de causer ce genre de souci d'accessibilité.
De plus, on se retrouve plus limité dans les possibilités de styler le forum.

Je propose donc qu'on le retire tout bonnement.

**Comment by dixy** [comment]
Je suis plutôt d'accord avec toi pour le retirer.
Personnellement, je ne vois pas trop l'intérêt de ce menu, il prend également de la place pour pas grand chose finalement.

**Comment by MissGeek** [comment]
Changement effectué !
